### ISSUE TITLE
Merge Sort page

### ISSUE THREAD

**Issue by sayanroy-bash** [sayanroy-bash/Code-Visualizer#3]

**Comment by vivekkmrpaswan** [comment]
Added merge sort

<img width="845" alt="image" src="https://github.com/user-attachments/assets/9c08c2b8-1367-4400-8279-479b90f3e71a">

**Comment by vivekkmrpaswan** [comment]
updated the merge_sort funtionality

<img width="637" alt="image" src="https://github.com/user-attachments/assets/d4e2a20c-a103-4264-a463-74b0db148551">
